name: Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.0'
        modules: 'qt5compat qtshadertools qtsvg'
        
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
        
    - name: Install cbindgen
      run: cargo install cbindgen
      
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v5
      
    - name: Configure
      run: |
        ./configure.ps1 --generator=Ninja CMAKE_BUILD_TYPE=$env:BUILD_TYPE
      shell: pwsh
      
    - name: Build
      run: cmake --build build --config $env:BUILD_TYPE
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpgmtranslate-windows-x64
        path: build/target/bin/rpgmtranslate.exe
